spring:
  application:
    name: gwangju-talent-festival-server

  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  access-token-key: ${ACCESS_TOKEN_KEY}
  refresh-token-key: ${REFRESH_TOKEN_KEY}
#  access-token-expires: 900000        # 15?
#  refresh-token-expires: 1209600000   # 14?
  access-token-expires: 1000000000000000000000000000
  refresh-token-expires: 1000000000000000000000000000


thirdparty:
  ncp:
    service-id: ${NCP_SERVICE_ID}
    access-key: ${NCP_ACCESS_KEY}
    secret-key: ${NCP_SECRET_KEY}
    phone-number: ${NCP_PHONE_NUMBER}

cors:
  allowed-origins:
    - "http://localhost:3000"
    - "https://광탈페.kr"
    - "https://www.광탈페.kr"
    - "https://xn--hc0b809dz3b.kr"
    - "https://www.xn--hc0b809dz3b.kr"